name: 📄 Documentation Issue
description: File an issue/update related to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file this documentation issue!
  - type: textarea
    id: "current-state"
    attributes:
      label: Current State
      description: Current state of the documentation page with possible links and screenshots
      placeholder: The "Getting Started" page does not fully explain...
      value: |
        **Description of the current state/issue**:

        **Link to the page**:

        **Screenshots (if relevant)**:
  - type: textarea
    id: "desired-state"
    attributes:
      label: Desired State
      description: How should the docs look like instead?
      placeholder: The page should instead explain...
      value: |
        **Description of the change you are proposing**:
  - type: dropdown
    id: "is-working"
    attributes:
      label: Would you like to fix this issue?
      description: You can choose to fix this issue yourself or let other contributors in the community fix it
      options: ["Yes! Count me in", "No. Please assign another contributor"]
