name: 🖥 Website Issue
description: File an issue to update the website
title: "[Site]: "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this site update!
  - type: textarea
    id: "current-state"
    attributes:
      label: Current State
      description: Current state of the website with possible links and screenshots
      placeholder: The image in the homepage is not aligned properly...
      value: |
        **Description of the current state/issue**:

        **Link to the page**:

        **Screenshots (if relevant)**:
  - type: textarea
    id: "desired-state"
    attributes:
      label: Desired State
      description: How should the site look like instead?
      placeholder: The image should instead be aligned...
      value: |
        **Description of the change you are proposing**:
  - type: dropdown
    id: "is-working"
    attributes:
      label: Would you like to fix this issue?
      description: You can choose to fix this issue yourself or let other contributors in the community fix it
      options: ["Yes! Count me in", "No. Please assign another contributor"]
