module.exports = [
  {
    name: 'APISIX®',
    nameInParamCase: 'apisix',
    description: 'A dynamic, real-time, high-performance API gateway.',
    shape: 'triangle',
    color: '#e8433e',
    githubRepo: 'apache/apisix',
    version: '3.0.0',
    releaseDate: '2022-11-02',
    firstDocPath: '/getting-started',
  },
  {
    name: 'APISIX® Dashboard',
    nameInParamCase: 'dashboard',
    description:
      'Designed to make it as easy as possible for users to operate Apache APISIX through a frontend interface.',
    shape: 'square',
    color: '#10B981',
    githubRepo: 'apache/apisix-dashboard',
    version: '2.13.0',
    releaseDate: '2022-06-01',
    firstDocPath: '/USER_GUIDE',
  },
  {
    name: 'APISIX® Ingress Controller',
    nameInParamCase: 'ingress-controller',
    description: 'An Apache APISIX control plane component.',
    shape: 'hexagon',
    color: '#2563EB',
    githubRepo: 'apache/apisix-ingress-controller',
    version: '1.3.0',
    releaseDate: '2021-10-17',
    firstDocPath: '/getting-started',
  },
  {
    name: 'APISIX® Helm Charts',
    nameInParamCase: 'helm-chart',
    description: 'An Apache APISIX Helm Charts provide the installation of Apache APISIX components for kubernetes.',
    shape: 'pentagon',
    color: '#C71585',
    githubRepo: 'apache/apisix-helm-chart',
    version: '0.4.0',
    releaseDate: '2021-03-12',
    firstDocPath: '/apisix',
  },
  {
    name: 'APISIX® Docker',
    nameInParamCase: 'docker',
    description: 'Docker tooling for Apache APISIX.',
    shape: 'diamond',
    color: '#FFD700',
    githubRepo: 'apache/apisix-docker',
    version: '1.0.0',
    releaseDate: '2020-12-1',
    firstDocPath: '/build',
  },
  {
    name: 'APISIX® Java Plugin Runner',
    nameInParamCase: 'java-plugin-runner',
    description: 'Runs Apache APISIX plugins written in Java. Implemented as a sidecar that accompanies Apache APISIX.',
    shape: 'star',
    color: '#FB9300',
    githubRepo: 'apache/apisix-java-plugin-runner',
    version: '0.4.0',
    releaseDate: '2022-11-11',
    firstDocPath: '/development',
  },
  {
    name: 'APISIX® Go Plugin Runner',
    nameInParamCase: 'go-plugin-runner',
    description: 'Runs Apache APISIX plugins written in Go. Implemented as a sidecar that accompanies Apache APISIX.',
    shape: 'octagon',
    color: '#3B14A7',
    githubRepo: 'apache/apisix-go-plugin-runner',
    version: '0.5.0',
    releaseDate: '2022-11-10',
    firstDocPath: '/getting-started',
  },
  {
    name: 'APISIX® Python Plugin Runner',
    nameInParamCase: 'python-plugin-runner',
    description: 'Runs Apache APISIX plugins written in Python. Implemented as a sidecar that accompanies Apache APISIX.',
    shape: 'shield',
    color: '#1296DB',
    githubRepo: 'apache/apisix-python-plugin-runner',
    version: '0.2.0',
    releaseDate: '2022-03-04',
    firstDocPath: '/getting-started',
  },
];
