module.exports = [
  {
    name: 'APISIX®',
    nameInParamCase: 'apisix',
    description: 'A dynamic, real-time, high-performance API gateway.',
    shape: 'triangle',
    color: '#e8433e',
    githubRepo: 'apache/apisix',
    githubBranch: 'master',
    downloadPath: 'apisix/3.9.1/apache-apisix-3.9.1-src',
    dockerhubPath: 'apisix',
    version: '3.9.1',
    LTSDownloadPath: 'apisix/3.2.2/apache-apisix-3.2.2-src',
    LTSVersion: '3.2.2',
    releaseDate: '2024-04-29',
    firstDocPath: '/getting-started',
  },
  {
    name: 'APISIX® Dashboard',
    nameInParamCase: 'dashboard',
    description:
      'Designed to make it as easy as possible for users to operate Apache APISIX through a frontend interface.',
    shape: 'square',
    color: '#10B981',
    githubRepo: 'apache/apisix-dashboard',
    githubBranch: 'master',
    downloadPath: 'apisix/dashboard/3.0.0/apache-apisix-dashboard-3.0.0-src',
    dockerhubPath: 'apisix-dashboard',
    version: '3.0.0',
    releaseDate: '2023-02-01',
    firstDocPath: '/USER_GUIDE',
  },
  {
    name: 'APISIX® Ingress Controller',
    nameInParamCase: 'ingress-controller',
    description: 'APISIX Ingress Controller for Kubernetes.',
    shape: 'hexagon',
    color: '#2563EB',
    githubRepo: 'apache/apisix-ingress-controller',
    githubBranch: 'master',
    downloadPath: 'apisix/ingress-controller/1.6.0/apache-apisix-ingress-controller-1.6.0-src',
    dockerhubPath: 'apisix-ingress-controller',
    version: '1.6.0',
    releaseDate: '2022-12-30',
    firstDocPath: '/getting-started',
  },
  {
    name: 'APISIX® Java Plugin Runner',
    nameInParamCase: 'java-plugin-runner',
    description: 'Runs Apache APISIX plugins written in Java. Implemented as a sidecar that accompanies Apache APISIX.',
    shape: 'star',
    color: '#FB9300',
    githubRepo: 'apache/apisix-java-plugin-runner',
    githubBranch: 'main',
    downloadPath: 'apisix/java-plugin-runner/0.4.0/apisix-java-plugin-runner-0.4.0-src',
    version: '0.4.0',
    releaseDate: '2022-11-11',
    firstDocPath: '/development',
  },
  {
    name: 'APISIX® Go Plugin Runner',
    nameInParamCase: 'go-plugin-runner',
    description: 'Runs Apache APISIX plugins written in Go. Implemented as a sidecar that accompanies Apache APISIX.',
    shape: 'octagon',
    color: '#3B14A7',
    githubRepo: 'apache/apisix-go-plugin-runner',
    githubBranch: 'master',
    downloadPath: 'apisix/go-plugin-runner/0.5.0/apisix-go-plugin-runner-0.5.0-src',
    version: '0.5.0',
    releaseDate: '2022-11-10',
    firstDocPath: '/getting-started',
  },
  {
    name: 'APISIX® Python Plugin Runner',
    nameInParamCase: 'python-plugin-runner',
    description: 'Runs Apache APISIX plugins written in Python. Implemented as a sidecar that accompanies Apache APISIX.',
    shape: 'shield',
    color: '#1296DB',
    githubRepo: 'apache/apisix-python-plugin-runner',
    githubBranch: 'master',
    downloadPath: 'apisix/python-plugin-runner/0.2.0/apisix-python-plugin-runner-0.2.0-src',
    version: '0.2.0',
    releaseDate: '2022-03-04',
    firstDocPath: '/getting-started',
  },
];
