module.exports = [
  {
    groupName: 'PMC',
    members: [
      {
        name: 'Ayeshmantha Perera',
        username: 'akayeshmantha',
        githubUsername: 'Akayeshmantha',
        avatarUrl: 'https://avatars.githubusercontent.com/u/20354461?v=4',
      },
      {
        name: 'Hui Li',
        username: 'yousa',
        githubUsername: 'Miss-you',
        avatarUrl: 'https://avatars.githubusercontent.com/u/3816205?v=4',
      },
      {
        name: 'Jiayu Qiu',
        username: 'qiujiayu',
        githubUsername: 'qiujiayu',
        avatarUrl: 'https://avatars.githubusercontent.com/u/3702914?v=4',
      },
      {
        name: 'JinChao Shuai',
        username: 'shuaijinchao',
        githubUsername: 'shuaijinchao',
        avatarUrl: 'https://avatars.githubusercontent.com/u/8529452?v=4',
      },
      {
        name: 'Justin Mclean',
        username: 'jmclean',
        githubUsername: 'justinmclean',
        avatarUrl: 'https://avatars.githubusercontent.com/u/144504?v=4',
      },
      {
        name: 'Junxu Chen',
        username: 'chenjunxu',
        githubUsername: 'nic-chen',
        avatarUrl: 'https://avatars.githubusercontent.com/u/33000667?v=4',
      },
      {
        name: 'Kevin Ratnasekera',
        username: 'djkevincr',
        githubUsername: 'djkevincr',
        avatarUrl: 'https://avatars.githubusercontent.com/u/1346010?v=4',
      },
      {
        name: 'Lang Wang',
        username: 'totemofwolf',
        githubUsername: 'totemofwolf',
        avatarUrl: 'https://avatars.githubusercontent.com/u/1818214?v=4',
      },
      {
        name: 'Ling Li',
        username: 'liling',
        githubUsername: 'lilien1010',
        avatarUrl: 'https://avatars.githubusercontent.com/u/3814966?v=4',
      },
      {
        name: 'Linsir Wu',
        username: 'linsir',
        githubUsername: 'linsir',
        avatarUrl: 'https://avatars.githubusercontent.com/u/4339659?v=4',
      },
      {
        name: 'Ming Wen',
        username: 'wenming',
        githubUsername: 'moonming',
        avatarUrl: 'https://avatars.githubusercontent.com/u/26448043?v=4',
      },
      {
        name: 'Nirojan Selvanathan',
        username: 'sshniro',
        githubUsername: 'sshniro',
        avatarUrl: 'https://avatars.githubusercontent.com/u/13045528?v=4',
      },
      {
        name: 'Sheng Wu',
        username: 'wusheng',
        githubUsername: 'wu-sheng',
        avatarUrl: 'https://avatars.githubusercontent.com/u/5441976?v=4',
      },
      {
        name: 'Vinci',
        username: 'vinci',
        githubUsername: 'ShiningRush',
        avatarUrl: 'https://avatars.githubusercontent.com/u/24238012?v=4',
      },
      {
        name: 'Von Gosling',
        username: 'vongosling',
        githubUsername: 'vongosling',
        avatarUrl: 'https://avatars.githubusercontent.com/u/635581?v=4',
      },
      {
        name: 'Wei Jin',
        username: 'kvn',
        githubUsername: 'gxthrj',
        avatarUrl: 'https://avatars.githubusercontent.com/u/4413028?v=4',
      },
      {
        name: 'Wei Liu',
        username: 'agile6v',
        githubUsername: 'agile6v',
        avatarUrl: 'https://avatars.githubusercontent.com/u/2017491?v=4',
      },
      {
        name: 'Willem Ning Jiang',
        username: 'ningjiang',
        githubUsername: 'WillemJiang',
        avatarUrl: 'https://avatars.githubusercontent.com/u/219644?v=4',
      },
      {
        name: 'Xiran Liu',
        username: 'liuxiran',
        githubUsername: 'liuxiran',
        avatarUrl: 'https://avatars.githubusercontent.com/u/2561857?v=4',
      },
      {
        name: 'YuanSheng Wang',
        username: 'membphis',
        githubUsername: 'membphis',
        avatarUrl: 'https://avatars.githubusercontent.com/u/6814606?v=4',
      },
      {
        name: 'Zexuan Luo',
        username: 'spacewander',
        githubUsername: 'spacewander',
        avatarUrl: 'https://avatars.githubusercontent.com/u/4161644?v=4',
      },
      {
        name: 'Zhiyuan',
        username: 'juzhiyuan',
        githubUsername: 'juzhiyuan',
        avatarUrl: 'https://avatars.githubusercontent.com/u/2106987?v=4',
      },
      {
        name: 'Chao Zhang',
        username: 'tokers',
        githubUsername: 'tokers',
        avatarUrl: 'https://avatars.githubusercontent.com/u/10428333?v=4',
      },
      {
        name: 'Zeping Bai',
        username: 'bzp2010',
        githubUsername: 'bzp2010',
        avatarUrl: 'https://avatars.githubusercontent.com/u/8078418?v=4',
      },
      {
        name: 'Jintao Zhang',
        username: 'zhangjintao',
        githubUsername: 'tao12345666333',
        avatarUrl: 'https://avatars.githubusercontent.com/u/3264292?v=4',
      },
      {
        name: 'Guosheng Yang',
        username: 'dabue',
        githubUsername: 'dabue',
        avatarUrl: 'https://avatars.githubusercontent.com/u/53054094?v=4',
      },
      {
        name: 'ZhengSong Tu',
        username: 'tzssangglass',
        githubUsername: 'tzssangglass',
        avatarUrl: 'https://avatars.githubusercontent.com/u/30819887?v=4',
      },
    ],
  },
  {
    groupName: 'Committer',
    members: [
      {
        name: 'acmly',
        username: 'yangli',
        githubUsername: 'JanLi-air',
        avatarUrl: 'https://avatars.githubusercontent.com/u/55779084?v=4',
      },
      {
        name: 'Joey Ma',
        username: 'majunjie',
        githubUsername: 'imjoey',
        avatarUrl: 'https://avatars.githubusercontent.com/u/2542401?v=4',
      },
      {
        name: 'Ke Tang',
        username: 'tangke',
        githubUsername: 'supermario1990',
        avatarUrl: 'https://avatars.githubusercontent.com/u/8428531?v=4',
      },
      {
        name: 'Li Zhiyong',
        username: 'lizhiyong',
        githubUsername: 'zhiyong0804',
        avatarUrl: 'https://avatars.githubusercontent.com/u/15864088?v=4',
      },
      {
        name: 'Shuyang Wu',
        username: 'shuyangw',
        githubUsername: 'yiyiyimu',
        avatarUrl: 'https://avatars.githubusercontent.com/u/34589752?v=4',
      },
      {
        name: 'Suo Zhang',
        username: 'coolsoul',
        githubUsername: 'soulsoul',
        avatarUrl: 'https://avatars.githubusercontent.com/u/4963471?v=4',
      },
      {
        name: 'Xinxin Zhu',
        username: 'starsz',
        githubUsername: 'starsz',
        avatarUrl: 'https://avatars.githubusercontent.com/u/25628854?v=4',
      },
      {
        name: 'Yi Sun',
        username: 'sunyi',
        githubUsername: 'LiteSun',
        avatarUrl: 'https://avatars.githubusercontent.com/u/31329157?v=4',
      },
      {
        name: 'Yong Li',
        username: 'liyong',
        githubUsername: 'chnliyong',
        avatarUrl: 'https://avatars.githubusercontent.com/u/4197225?v=4',
      },
      {
        name: 'Chen Jin',
        username: 'Jaycean',
        githubUsername: 'Jaycean',
        avatarUrl: 'https://avatars.githubusercontent.com/u/36916582?v=4',
      },
      {
        name: 'Xingwang Li',
        username: 'okaybase',
        githubUsername: 'okaybase',
        avatarUrl: 'https://avatars.githubusercontent.com/u/75366457?v=4',
      },
      {
        name: 'Ling Samuel',
        username: 'lingsamuel',
        githubUsername: 'lingsamuel',
        avatarUrl: 'https://avatars.githubusercontent.com/u/14567045?v=4',
      },
      {
        name: 'Yeliang Wang',
        username: 'wang-yeliang',
        githubUsername: 'wang-yeliang',
        avatarUrl: 'https://avatars.githubusercontent.com/u/19886745?v=4',
      },
      {
        name: 'Shivam Singh',
        username: 'singhsh',
        githubUsername: '1502shivam-singh',
        avatarUrl: 'https://avatars.githubusercontent.com/u/57267960?v=4',
      },
      {
        name: 'Bisakh Mondal',
        username: 'bisakh',
        githubUsername: 'bisakhmondal',
        avatarUrl: 'https://avatars.githubusercontent.com/u/41498427?v=4',
      },
      {
        name: 'Yilin Zeng',
        username: 'yilinzeng',
        githubUsername: 'yzeng25',
        avatarUrl: 'https://avatars.githubusercontent.com/u/36651058?v=4',
      },
      {
        name: 'Sylvia Su',
        username: 'SylviaBABY',
        githubUsername: 'SylviaBABY',
        avatarUrl: 'https://avatars.githubusercontent.com/u/39793568?v=4',
      },
      {
        name: 'Yuan Bao',
        username: 'baoyuan',
        githubUsername: 'Baoyuantop',
        avatarUrl: 'https://avatars.githubusercontent.com/u/30611190?v=4',
      },
      {
        name: 'Qi Guo',
        username: 'guoqqqi',
        githubUsername: 'guoqqqi',
        avatarUrl: 'https://avatars.githubusercontent.com/u/72343596?v=4',
      },
      {
        name: 'Tao Yang',
        username: 'Young',
        githubUsername: 'SkyeYoung',
        avatarUrl: 'https://avatars.githubusercontent.com/u/48400568?v=4',
      },
      {
        name: 'Xin Rong',
        username: 'AlinsRan',
        githubUsername: 'AlinsRan',
        avatarUrl: 'https://avatars.githubusercontent.com/u/79972061?v=4',
      },
    ],
  },
];
