name: Sync Docs from projects

on:
  push:
    branches: [master]
  schedule:
    # Run everyday at 6:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
    - cron: "0 6 * * *"

jobs:
  pull-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Pull Docs
        run: |
          node pullDocs.js && git status

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: "docs: update docs (by GitHub Action)"
